// This request.rest file is used to test requests inside of vs code, makes testing easier. 

// ### three hashes are used to separate request tests. 
// format for requests: GET http://localhost:3000


GET http://localhost:3000/api/open/get_superhero_publishers


###

POST http://localhost:3000/create-client

###

POST http://localhost:3000/login


###

GET http://localhost:3000/getCredentials

###

GET http://localhost:3000/verify/ef32bb5d27c3b18ce081aa5b69920a7bb697f401

### 

POST http://localhost:3000/logout

###

POST http://localhost:8080/heroSearch
Content-Type: application/json

{
  "name": "as",
  "race": "",
  "publisher": "",
  "power": ""

}

###

POST http://localhost:3000/displayLists

###

POST http://localhost:3000/getHeroesByList
Content-Type: application/json

{
"heroList": "batman,superman,spider-man"
}


### 
// for the notificaiton debugging, but I couldn't get it to work. 
POST http://localhost:8080/createList
Content-Type: application/json

{
  "listName": "sdf",
  "listDesc": "description",
  "heroCollection": "superman",
  "createdBy": "Seth",
}